### ISSUE TITLE
pia-tools no longer in AUR?

### ISSUE THREAD

**Issue by bits01** [pschmitt/pia-tools#22]
https://aur.archlinux.org/packages/pia-tools/
returns 404 Not Found

**Comment by ethanmad** [comment]
Try again. I'm now maintaining it. As such, please report issues and submit PRs to my fork: [ethanmad/pia-tools](https://github.com/ethanmad/pia-tools).

**Comment by bits01** [comment]
Thank you for picking it up.

**Comment by pschmitt** [comment]
This repo's version is back in the AUR: https://aur.archlinux.org/packages/pia-tools-orig

**Comment by pschmitt** [comment]
NB: I had to rewrite the entire history in order to be able to use the same repo for both GitHub and the AUR.

**Comment by ethanmad** [comment]
@pschmitt 

1. I'll transfer `pia-tools` to you, so we can scrap the orig appendage.
2. It's a little confusing how the AUR works, but the souce repo and the AUR repo should be different. The AUR repo is a NEW containing only `PKGBUILD`, `.SRCINFO`, and install files (in this case `pia-tools.install`).

**Comment by pschmitt** [comment]
Okay, quick update:
1. I requested the `pia-tools-orig` to be removed
2. This is how I decided to do things. As you may have noticed I created a [new orphan branch](https://github.com/pschmitt/pia-tools/tree/aur) which essentially is a mirror of the AUR git repository. This workflow still is not optimal since you have to work with 2 remotes and 2 branches - but at least the there is only one repository. 
Each time a commit is made on the (Github) master branch it has to be cherry-picked on the `aur` branch and pushed to the AUR remote in order to get "live". Beware that AUR does not allow for any branches other than `master`, hence: `git push aur aur:master`

**Comment by ethanmad** [comment]
I like this solution. Cherry-picking is a great way to do this.
